### PR TITLE
Update xsimd for Android support.

### PR DESCRIPTION
**Pull request by atsushieno**
context: https://github.com/jatinchowdhury18/RTNeural/issues/80

This makes RTNeural just build on Android without disabling optimized `exp` and `exp10`.

### CODE REVIEW

**Comment by jatinchowdhury18** [comment]
Thanks for the PR!

This is a bit of a tricky one since the XSIMD folks removed `xsimd::transform` and `xsimd::reduce` without really offering a replacement. I'd rather not use the `std::` replacements since that would force RTNeural to depend on C++17, and I'd definitely prefer to keep C++14 compatibility. Additionally, the `std::` methods would likely be less performant in this context since they lose the explicit vectorization that the XSIMD methods provided.

Maybe the best option is to just copy [this file](https://github.com/xtensor-stack/xsimd/blob/2f7aa40d70073a9b1b757dd2f9166b19c7e83f2d/include/xsimd/stl/algorithms.hpp) to somewhere inside the RTNeural source tree (maybe `RTNeural/RTNeural/xsimd-algorithms/algorithms.hpp`), leave a comment saying why it's there, and then include it in common.h under the XSIMD section. Do you think that would work?

**Comment by atsushieno** [comment]
Yes, that sounds perfect. I will update this to make the changes later, but if you make it I appreciate that!

**Comment by atsushieno** [comment]
The changes are made as ^

**Comment by jatinchowdhury18** [comment]
Awesome, thanks! I decided to bump the XSIMD version up to 10.0.0, and use the `xsimd_api.hpp" header from within XSIMD, just to avoid having duplicates of any headers.

Once the CI is happy with everything, then I'll go ahead and merge this!

**Pull request merged**
